#!/bin/bash

# The internet interface
inetIface=eth0

# The wifi AP interface
brIface=wlan0

# ---- Port Forwarding config ---- #
# Enable NAT
sysctl -w net.ipv4.ip_forward=1
echo "  + NAT enabled"

# Setup iptables
iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -t nat -I POSTROUTING -o "$inetIface" -j MASQUERADE
echo "  + Set iptables for forwarding"

# ---- Services start ---- #
# Launch udhcpd
mkdir -p /var/lib/misc/
touch /var/lib/misc/udhcpd.leases
udhcpd -S -cf udhcpd.conf
echo "  + udhcpd"

# Launch hostapd
hostapd -B hostapd.conf
echo -e "  + hostapd\n"

