#!/bin/bash

# The internet interface
inetIface=wlan0

# The repeated interface
brIface=wlan1

installDir=/root/WifiRepeater
waitTime=10

# ---- Port Forwarding config ---- #
# Enable NAT
sysctl -w net.ipv4.ip_forward=1
echo "  + NAT enabled"

# Setup iptables
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
echo "  + Flushed iptables"

iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -t nat -I POSTROUTING -o "$inetIface" -j MASQUERADE
echo "  + Redefined iptables"

# ---- Services start ---- #
# Launch DHCPD
dhcpd "$brIface" -cf $installDir/dhcpd.conf
echo "  + dhcpd"

# Launch hostapd
hostapd -B $installDir/hostapd.conf
echo -e "  + hostapd\n"

# Check the connectivity and execute the "event/" script correspondent
while true
do
  # ---- Checking connectivity ---- #
  wget -q http://www.avilab.fr/projectFiles/wifiSum.txt -O /tmp/newCheckSum

  oldmd5=$(cat $installDir/originalCheckSum | md5sum -)
  newmd5=$(cat /tmp/newCheckSum | md5sum -)

  if [ "$newmd5" != "$oldmd5" ]
  then
	bash $installDir/events/stateDisconnected.sh
  else
    	bash $installDir/events/stateConnected.sh
  fi

  # ---- Checking Services ---- #
  if [ $(ps -ef | grep -v grep | grep dhcpd | wc -l) == 0 || $(ps -ef | grep -v grep | grep hostapd | wc -l) == 0 ]
  then
     bash $installDir/events/stateServiceError.sh
  fi
  sleep $waitTime
done
